name: Build HCI UART with DFU for Fanstel BM832

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: bm832_hci_uart

      - name: Initialize
        working-directory: bm832_hci_uart
        run: |
          west init -l
          west update
          west zephyr-export

      - name: Build firmware
        working-directory: bm832_hci_uart
        run: |
          west build -b fanstel_bm832 -s app_hci_uart_with_dfu

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: bm832_hci_uart/build/zephyr/zephyr.*

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: signed_firmware
          path: bm832_hci_uart/build/zephyr/app_signed.*

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware_for_update
          path: bm832_hci_uart/build/zephyr/app_update.*

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: test_firmware
          path: bm832_hci_uart/build/zephyr/app_test_update.*
