name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: bm832_hci_uart

      - name: Initialize
        working-directory: bm832_hci_uart
        run: |
          west init -l
          west update
          west zephyr-export

      - name: Build firmware
        working-directory: bm832_hci_uart
        run: |
          west build ../zephyr/samples/bluetooth/hci_uart -b fanstel_bm832

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: bm832_hci_uart/build/zephyr/zephyr.*
