# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
     - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: bm832_hci_uart

      - name: Initialize
        working-directory: bm832_hci_uart
        run: |
          west init -l
          west update
          west zephyr-export

      - name: Build firmware
        working-directory: bm832_hci_uart
        run: |
          west build ../zephyr/samples/bluetooth/hci_uart -b fanstel_bm832

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: release_${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: bm832_hci_uart/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Upload FW binary HEX
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bm832_hci_uart/build/zephyr/zephyr.hex
          asset_name: zephyr.hex
          asset_content_type: application/octet-stream

      - name: Upload FW binary BIN
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bm832_hci_uart/build/zephyr/zephyr.bin
          asset_name: zephyr.bin
          asset_content_type: application/octet-stream

      - name: Upload FW binary ELF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bm832_hci_uart/build/zephyr/zephyr.elf
          asset_name: zephyr.elf
          asset_content_type: application/octet-stream
        